### PR TITLE
Use foldMany1 in chunksOf instead of foldMany

### PR DESCRIPTION
**Pull request by harendra-kumar**
Need to run the benchmarks before merging.

### CODE REVIEW

**Review by pranaysashank — APPROVED** [review]

**Comment by harendra-kumar** [comment]
There is no change in allocations but I see regression in cpu time:

```
Benchmark                                                                                     default(0)(ms) default(1) - default(0)(%) default(2) - default(0)(%)
--------------------------------------------------------------------------------------------- -------------- -------------------------- --------------------------
FileSystem.Handle/o-1-space/reduce/read/chunks/S.arraysOf 1000                                        110.06                    +334.56                    +334.67
FileSystem.Handle/o-1-space/reduce/read/chunks/S.chunksOf 1 FL.sum                                    160.99                     +63.55                     +62.95
FileSystem.Handle/o-1-space/reduce/read/chunks/S.arraysOf 10                                          280.77                     +58.08                     +53.52
```

**Comment by harendra-kumar** [comment]
This could be because of the additional state jump in foldMany1 vs foldMany. But if we remove that then it does not fuse.

**Comment by harendra-kumar** [comment]
Measured some related benchmarks:

```
Benchmark                                                                                     default(0)(ms) default(1) - default(0)(%)
--------------------------------------------------------------------------------------------- -------------- --------------------------
FileSystem.Handle/o-1-space/reduce/read/chunks/S.chunksOf 1 (1/10)                                    104.49                      +0.04
FileSystem.Handle/o-1-space/reduce/read/chunks/S.chunksOf 10                                          252.11                     +70.83
FileSystem.Handle/o-1-space/reduce/read/chunks/S.chunksOf 1000                                        109.54                    +328.41

FileSystem.Handle/o-1-space/reduce/read/chunks/S.chunksOf 1 FL.sum                                    163.96                     +59.54
FileSystem.Handle/o-1-space/reduce/read/chunks/S.chunksOf 104857600 FL.sum                            118.02                      -0.70

FileSystem.Handle/o-1-space/reduce/read/chunks/S.parseMany (FL.take 1 FL.sum)                          84.51                      +0.83
FileSystem.Handle/o-1-space/reduce/read/chunks/S.parseMany (FL.take 104857600 FL.sum) (1/10)           10.16                      +2.52

FileSystem.Handle/o-1-space/reduce/read/chunks/S.foldMany (FL.take 1 FL.sum)                          163.76                      -0.16
FileSystem.Handle/o-1-space/reduce/read/chunks/S.foldMany (FL.take 104857600 FL.sum) (1/10)            11.38                      -0.69

FileSystem.Handle/o-1-space/reduce/read/chunks/S.foldMany1 (FL.take 1 FL.sum)                         260.58                      +0.22
FileSystem.Handle/o-1-space/reduce/read/chunks/S.foldMany1 (FL.take 104857600 FL.sum) (1/10)           10.46                      -3.57
```

It seems parseMany is faster. Need to check what are we doing differently in that one.

**Comment by harendra-kumar** [comment]
With the new changes we actually got an improvement in benchmarks with foldMany1:

```
FileSystem.Handle(cpuTime)                                                                                                                                                        
Benchmark                                                                                     default(0)(ms) default(1) - default(0)(%)                                           
--------------------------------------------------------------------------------------------- -------------- --------------------------         
FileSystem.Handle/o-1-space/reduce/read/chunks/S.chunksOf 104857600 FL.sum                            119.22                     -12.81
FileSystem.Handle/o-1-space/reduce/read/chunks/S.chunksOf 1 (1/10)                                    123.36                     -15.08
FileSystem.Handle/o-1-space/reduce/read/chunks/S.chunksOf 1 FL.sum                                    143.42                     -21.46
FileSystem.Handle/o-1-space/reduce/read/chunks/S.chunksOf 10                                          263.77                     -24.09
```

**Pull request merged**
