### PR TITLE
Replace /Internal/ annotation to /Pre-release/ and takeLE to take

### PR DESCRIPTION
**Pull request by rnjtranjan**
issue #963

### CODE REVIEW

**Comment by rnjtranjan** [comment]
Fix #914

**Comment by rnjtranjan** [comment]
Fix #804

**Review by harendra-kumar — APPROVED** [review]
squash the "Fix test build issue" commit into the previous takeLE commit.

**Review by adithyaov — COMMENTED** [review]
Looks fine. We can merge this once the fixup is done.

**Pull request merged**
