### PR TITLE
Avoid using dd, pipe data directly & truncate it using head

### PR DESCRIPTION
**Pull request by adithyaov**
dd is confusing to work with and has it's own idiosyncracies.

### CODE REVIEW

**Review by harendra-kumar — COMMENTED** [review]
Looks good, but need to test it on mac as we have changed the device to urandom. We can perhaps add a simple invocation (not too expensive to run, e.g. running a single benchmark with --quick option) of bench.sh in CI so that it can be tested automatically.

Also, we may want to change the location of the input data files to "dist-newstyle" so that we do not create big files at random places within the workspace.

**Comment by adithyaov** [comment]
@harendra-kumar Can we merge this? This will be implicitly tested on #745

**Review by harendra-kumar — APPROVED** [review]
The FileSystem.Handle benchmark run seems to be creating a directory named "benchmark-tmp/ " as well. I am not sure why, can you take a look at that too.

**Comment by adithyaov** [comment]
> The FileSystem.Handle benchmark run seems to be creating a directory named "benchmark-tmp/ " as well. I am not sure why, can you take a look at that too.

We are explicitly creating it. aka `scratchDir`

**Review by harendra-kumar — APPROVED** [review]

**Comment by adithyaov** [comment]
Merging this.

**Pull request merged**
