### PR TITLE
Streamly doesn't build with Stack on Mac OS

### PR DESCRIPTION
**Pull request by AliceRixte**
Added CI in order to investigate `stack build` failing  on Mac OS. See issue #2833.

### CODE REVIEW

**Comment by harendra-kumar** [comment]
You can do the following:

* comment out all other CIs
* use `disable_test: "y"`
* use `disable_bench: "y"`

**Comment by harendra-kumar** [comment]
The stack CIs are not able to start because of config issue in the yaml file:

```

Haskell CI
Error when evaluating 'continue-on-error' for job 'build'. .github/workflows/haskell.yml (Line: 65, Col: 24): Unexpected value ''
```

You can remove the `continue-on-error` section, the `name` section, `fail-fast` and `ignore_error` in all CIs:

```
    continue-on-error: ${{ matrix.ignore_error }}
      fail-fast: true
        name:
          - 9.10.1-Werror

            ignore_error: false
```

**Comment by harendra-kumar** [comment]
In [stack.yaml here](https://github.com/composewell/streamly/blob/master/stack.yaml), comment out the extra deps. You can also comment out `test` and `benchmark` under packages section.

I have changed the settings of the repo so it should not require explicit approval to run CIs on your PR.

**Comment by harendra-kumar** [comment]
@AliceRixte I added a CI with latest stack nightly and used a verbose option as well to see if it gives any info. Can you raise an issue on the stack repo mentioning the output of this CI: https://github.com/composewell/streamly/actions/runs/11062893476/job/30738127480?pr=2842

**Comment by AliceRixte** [comment]
@harendra-kumar  That's great ! Thank you so much !

**Pull request closed without merging**
