### PR TITLE
Fix benchmark regression CI

### PR DESCRIPTION
**Pull request by adithyaov**

### CODE REVIEW

**Comment by adithyaov** [comment]
I'm able to compile this locally. I wonder what's wrong with the CI.

**Comment by harendra-kumar** [comment]
streamly-coreutils seems to be requiring streamly < 0.9
```
[__1] rejecting: streamly-coreutils-0.1.0.0 (conflict: streamly==0.9.0,
streamly-coreutils => streamly>=0.8.0 && <0.9)
```

**Comment by adithyaov** [comment]
It's not picking the proper commit given in `cabal.project.report`. I wonder why. Something wrong with the CI?

**Comment by adithyaov** [comment]
Ah, something is wrong with the CI. It isn't running on the current commit.

**Pull request closed without merging**
