### PR TITLE
Updated types of bindWith, concatMapWith, concatMapBy to remove expli…

### PR DESCRIPTION
**Pull request by tymefighter**
…cit forall

### CODE REVIEW

**Comment by harendra-kumar** [comment]
@pranaysashank can you please take a look at this and merge it? 

There are other combinators as well like:

* concatMapIterateWith
* concatMapTreeWith
* concatMapLoopWith
* concatMapTreeYieldLeavesWith

These can also be changed similarly?

**Comment by harendra-kumar** [comment]
@tymefighter can you make the other changes as well, the ones I suggested above. We can merge all of them together.

**Comment by tymefighter** [comment]
I'll do it today

**Comment by harendra-kumar** [comment]
We can hold it off until we start committing breaking changes to the master branch.

**Comment by pranaysashank** [comment]
Merged into the branch `staging-0.8.0` with 52d41aa5d654c478579fd0b84ba666c8031bc070

**Pull request closed without merging**
