### PR TITLE
Fix build for primitive-0.6.3.0. Solves #466.

### PR DESCRIPTION
**Pull request by adithyaov**

### CODE REVIEW

**Comment by harendra-kumar** [comment]
When adding this module I asked Adithya to keep only the bare minimum that we need but he argued that there is no harm in keeping everything. Unwanted code is always a maintenance headache plus added compilation times. We should try to keep the bare minimum needed or if we expect something to be used in future.

**Comment by adithyaov** [comment]
> This entire module is a mess that ideally we shouldn't have to maintain.

I agree. At that point, it seemed like a good idea because I thought I'll use these functions in `Streamly.External.Text`. I think it's better to keep it at bare minimum like @harendra-kumar suggested.

**Comment by adithyaov** [comment]
Hopefully users of streamly did not use that part of the code. Removing unecessary code also got rid of the CPP macros which is nice.

**Comment by harendra-kumar** [comment]
Looks good. @pranaysashank please merge if it looks fine to you as well.

**Comment by harendra-kumar** [comment]
Can we add a changelog entry about the build fix?

**Comment by pranaysashank** [comment]
Please fix the failing builds

**Pull request closed without merging**
