### PR TITLE
Add an inspection test for #214

### PR DESCRIPTION
**Pull request by neongreen**
This is how it looks when the test fails:

```
test/inspection.hs:33:1: test214 does not contain dictionary values failed:
    go_sdTh = \ (ds1 [Dmd=<S,1*U>] :: ghc-prim-0.5.3:GHC.Types.SPEC)
    [... many more lines stripped --@neongreen]

### CODE REVIEW

**Comment by harendra-kumar** [comment]
This is cool! Thanks @neongreen .

Need to see why the windows build is failing.

**Comment by harendra-kumar** [comment]
We are seeing this error for windows build:

```
Preprocessing test suite 'inspection' for streamly-0.6.1..
Building test suite 'inspection' for streamly-0.6.1..
ghc.exe: unable to load package `streamly-0.6.1'
ghc.exe:  | C:\pkg\.stack-work\dist\e626a42b\build\HSstreamly-0.6.1-I9Hjk7PFZ1Zikv4KhF952.o: unknown symbol `clock_gettime'
```

Streamly is being built with `clock_gettime` as we can see in the configure logs. `clock_gettime` is usually not available on windows but I guess it is coming from the `mingw` installation. It seems to be using clock_gettime from mingw in earlier tests too (before this PR) that are passing.

Looks like the execution of ghc with inspection testing plugin is failing to resolve the symbol `clock_gettime`. Perhaps it is not having the appropriate mingw library in the linker path when executing?

This may require some debugging, we can even disable inspection testing plugin for windows build.

**Comment by pranaysashank** [comment]
It seems to be a problem with streamly, rather than inspection-testing. We're using `clock_gettime` in `Streamly/Time/Clock.hsc`. There is this error in the logs a few lines above
```
streamly> build (lib + test + bench)
Preprocessing library for streamly-0.6.1..
Failed to remove file .stack-work\dist\e626a42b\build\Streamly\Time\Clock_hsc_make.exe; 
error= .stack-work\dist\e626a42b\build\Streamly\Time\Clock_hsc_make.exe: DeleteFile "\\\\?
\\C:\\pkg\\.stack-work\\dist\\e626a42b\\build\\Streamly\\Time\\Clock_hsc_make.exe": 
permission denied (Access is denied.)
Failed to remove file .stack-work\dist\e626a42b\build\Streamly\FileSystem\IOVec_hsc_make.exe;
 error= .stack-work\dist\e626a42b\build\Streamly\FileSystem\IOVec_hsc_make.exe: DeleteFile
 "\\\\?\\C:\\pkg\\.stack-work\\dist\\e626a42b\\build\\Streamly\\FileSystem\\IOVec_hsc_make.exe":
 permission denied (Access is denied.)
Building library for streamly-0.6.1.
```

**Comment by pranaysashank** [comment]
Can we trigger a rebuild in AppVeyor manually?

**Comment by harendra-kumar** [comment]
I saw those errors earlier but they did not seem fatal, just a failure in cleanup. Anyway, I fired a rebuild and it did not have those errors this time but still failed with the same `clock_gettime` symbol error.

**Comment by neongreen** [comment]
It's not essential to run this test on Windows, so I've taken the liberty of disabling it.

**Comment by harendra-kumar** [comment]
Great! Thanks!

I am wondering if we can add inspection test assertions in the bechmark code itself e.g. in `LinearOps.hs`. We can perhaps use CPP conditionals to build for inspection testing or for benchmarking. That way we can reuse code and we will always remember to add inspection tests and benchmarks together.

**Comment by harendra-kumar** [comment]
Thanks @neongreen ! This is a great way to keep a tab on performance regressions.

**Pull request merged**
