### PR TITLE
hie.yaml: Add a hie.yaml file for Haskell Language Server

### PR DESCRIPTION
**Pull request by SanchayanMaity**
This is helpful for Haskell Language Server to detect project
configuration and set up GHC.

Generated using gen-hie from the implicit-hie project.

Signed-off-by: Sanchayan Maity <maitysanchayan@gmail.com>

### CODE REVIEW

**Comment by pranaysashank** [comment]
The generated file contains wrong paths for the test components Prelude.*.  Also does the component listed for benchmark files actually work?

**Comment by harendra-kumar** [comment]
@SanchayanMaity thanks for the PR. Are you planning to make the test and benchmark components work?

**Comment by harendra-kumar** [comment]
I see this error when running `ghcide`:

```
ghcide: CradleError (ExitFailure 1) ["Failed to parse result of calling cabal","","cabal: Unknown target 'streamly:bench:/*.hs'.\nThe package streamly has no component 'bench'.\n\n\n",""]
```

**Comment by SanchayanMaity** [comment]
@harendra-kumar Yes, I want to make the test and benchmark components work. Yet to find a solution. I have not tested with `ghcide`, was using `Haskell Language Server`. But, I guess HLS does not work because `ghcide` doesn't.

**Comment by harendra-kumar** [comment]
I tried running ghcide but could not get past this error:

```
Step 4/6, Cradle 1/1: Loading GHC Session
ghcide: CradleError ExitSuccess ["Multi Cradle: No prefixes matched","pwd: /Users/vol/vemba/composewell-tech/Eng/projects/streamly/streamly1","filepath: /Users/vol/vemba/composewell-tech/Eng/projects/streamly/streamly1","prefixes:","(\"./src\",Cabal {component = Just \"streamly:lib:streamly\"})"]
```

I tried writing `hie.yaml` in the same way as in the ghcide repo.

**Comment by harendra-kumar** [comment]
I cannot find documentation on how to write a working `hie.yaml`. That's basic. Maybe I did not dig carefully.

**Comment by pranaysashank** [comment]
@harendra-kumar https://github.com/mpickering/hie-bios/ . I can share mine, I think I should have it from long ago

**Comment by pranaysashank** [comment]
`ghcide` used to be behind the times with hie-bios, I used to just patch the latest version in. But I stopped using both the language servers long ago

**Comment by pranaysashank** [comment]
This is my config from long ago, hopefully it still works.
```cabal
cradle:
  cabal:
    - path: "./src"
      component: "lib:streamly"
    - path: "./examples/ListDir.hs"
      component: "exe:ListDir"
    - path: "./test/Prop.hs"
      component: "test:properties"

dependencies:
  - streamly.cabal
```

**Comment by harendra-kumar** [comment]
It did not work. ghcide gives the same error. I tried without an hie.yaml and in that case I think it fails because of CPP macros. maybe we need to enable the extensions explicitly. Does it look at the cabal file at all to get the build information?

It may not be worth spending time, it seems immature as of now.

**Comment by pranaysashank** [comment]
We can wait until the integration work is complete https://github.com/haskell/haskell-language-server. But I didn't have any problems haskell-ide-engine (other than template-haskell), I don't know about ghcide though.

**Comment by pranaysashank** [comment]
#732 adds a hie.yaml file.

**Pull request closed without merging**
