### PR TITLE
Use extensions by default instead of using them per file

### PR DESCRIPTION
**Pull request by harendra-kumar**
Most extensions do not show any compilation, functionality or performance related issues. Except for the following three we can enable all others:

* UndecidableInstances -- Don't want to use unless indicated
* TypeFamilies         -- Causes large regressions and improvements too!
* UnboxedTuples        -- interferes with (#.)

We need to investigate TypeFamilies, why does it cause regressions and improvements.

### CODE REVIEW

**Comment by pranaysashank** [comment]
* Do we add `TemplateHaskell` to the list of default-extensions? I think
it might create confusing error messages.
* Use `default-extensions` for tests and benchmarks?

**Comment by harendra-kumar** [comment]
No for `TemplateHaskell`, yes for tests and benchmarks.

**Comment by pranaysashank** [comment]
@harendra-kumar Can you restart appveyor?

**Comment by harendra-kumar** [comment]
restarted.

**Pull request merged**
