### PR TITLE
Fix GHCJS build taking too much memory

### PR DESCRIPTION
**Pull request by harendra-kumar**

### CODE REVIEW

**Comment by harendra-kumar** [comment]
Fixes #1207 . Fixes #1208 .

**Comment by adithyaov** [comment]
This is more like bypassing the check, not fixing the problem. We should still keep the issues open and update them accordingly.

**Review by adithyaov — APPROVED** [review]

**Comment by harendra-kumar** [comment]
> This is more like bypassing the check, not fixing the problem. We should still keep the issues open and update them accordingly.

I will close them unless you have a plan on how to fix it.

**Comment by adithyaov** [comment]
> I will close them unless you have a plan on how to fix it.

I don't, yet.

**Pull request merged**
