### PR TITLE
rearrange some functions in prelude

### PR DESCRIPTION
**Pull request by harendra-kumar**
According to the correct categories they belong to.

Let me know if it badly affects someone's pending changes.

### CODE REVIEW

**Comment by Veladus** [comment]
I currently have some pending work done in Prelude. This PR wouldn't effect my work too badly, but I suppose a similar PR would be needed afterwards.

**Comment by harendra-kumar** [comment]
Let me know if it is better for you to go first and then do it at once, I will hold off in that case.

**Comment by Veladus** [comment]
I think doing the cleanup in one go would be better 😃

**Comment by harendra-kumar** [comment]
Yeah, that will be more efficient. Thanks for letting me know!

**Comment by harendra-kumar** [comment]
This is obsolete now, dropping it.

**Pull request closed without merging**
