### PR TITLE
Add another implementation of Min

### PR DESCRIPTION
**Pull request by rnjtranjan**

### CODE REVIEW

**Comment by rnjtranjan** [comment]
supposed to be faster but benchmark show slower:
  
  minimum (window size 100):             OK (0.32s)
      4.98 ms ± 259 μs
    minimum (window size 1000):            OK (0.21s)
      13.6 ms ± 818 μs
    minimum2 (window size 1000):           OK (0.22s)
      73.5 ms ± 4.8 ms

**Comment by harendra-kumar** [comment]
This is a scan benchmark. Can we also try the fold benchmarks? Also try descending order vs ascending order.

We have descending order benchmarks under fold category, we can try the same for postscan as well:

```
        , benchWith sourceDescendingInt numElements
            "minimum descending (window size 1000)"
(Ring.slidingWindow 1000 Window.minimum)
```

**Comment by rnjtranjan** [comment]
for 10,100 size:
  scan
    minimum (window size 10):              OK (0.15s)
      4.92 ms ± 461 μs
    minimum (window size 100):             OK (0.16s)
      4.98 ms ± 414 μs
    minimum (window size 1000):            OK (0.20s)
      13.5 ms ± 722 μs
    minimum2 (window size 10):             OK (1.14s)
      2.21 ms ± 103 μs
    minimum2 (window size 100):            OK (0.31s)
      9.95 ms ± 550 μs
    minimum2 (window size 1000):           OK (0.22s)
      72.9 ms ± 3.0 ms

**Comment by rnjtranjan** [comment]
Folds are performing better.
fold
    minimum (window size 100):              OK (0.23s)
      3.66 ms ± 170 μs
    minimum (window size 1000):             OK (0.11s)
      8.17 ms ± 679 μs
    minimum descending (window size 1000):  OK (0.22s)
      7.11 ms ± 345 μs
    minimum ascending (window size 1000):   OK (0.18s)
      11.9 ms ± 742 μs
    minimum2 (window size 100):             OK (0.21s)
      818  μs ±  42 μs
    minimum2 (window size 1000):            OK (0.22s)
      852  μs ±  42 μs
    minimum2 descending (window size 1000): OK (0.13s)
      4.04 ms ± 385 μs
    minimum2 ascending (window size 1000):  OK (0.13s)
      4.13 ms ± 346 μs

**Review by rnjtranjan — COMMENTED** [review]
Looks good

**Comment by rnjtranjan** [comment]
Fixes:https://github.com/composewell/streamly/issues/1591

**Pull request merged**
