### PR TITLE
Add support for new line boundary split and re position the file handle  till n…

### PR DESCRIPTION
**Pull request by rnjtranjan**
…ew line

### CODE REVIEW

**Review by harendra-kumar — CHANGES_REQUESTED** [review]
We do not need these APIs.

Please use `splitOn :: (IsStream t, MonadIO m) => Word8 -> t m (Array Word8) -> t m (Array Word8) ` from the ArrayStream module. You can use splitOn on a stream of Array Word8 to get arrays aligned on newlines.

**Comment by rnjtranjan** [comment]
> We do not need these APIs.
> 
> Please use `splitOn :: (IsStream t, MonadIO m) => Word8 -> t m (Array Word8) -> t m (Array Word8) ` from the ArrayStream module. You can use splitOn on a stream of Array Word8 to get arrays aligned on newlines.

I just tried this API, the output has coalesced. 

Output without splitOn API:
("/home/ranjeetr/composewell-private/io-relay/aa3.txt","aaaaaaaaaaaaaaaa")
("/home/ranjeetr/composewell-private/io-relay/aa3.txt","bbbbbbbbbbbbbbbbbbb")
("/home/ranjeetr/composewell-private/io-relay/aa3.txt","cccccccccccDDDDDDDDDDDDDDDDDDDssssssssssssssss")

Output with splitOn API:
("/home/ranjeetr/composewell-private/io-relay/aa3.txt","aaaaaaaaaaaaaaaabbbbbbbbbbbbbbbbbbbcccccccccccDDDDDDDDDDDDDDDDDDDssssssssssssssss")

As per fluent bit documentation: each line of a log file is treated as a separate record that can be parsed by any third party.
If we combined multiple lines in a single record then parsing will be complicated.

**Comment by harendra-kumar** [comment]
If you just want to get lines from a stream that's even simpler. See `splitWithSuffix` in Streamly.Internal.Prelude and `lines` in Streamly.Internal.Unicode.Stream. On a Word8 stream you can simply use `splitOnSuffix (== 10)`.

**Comment by rnjtranjan** [comment]
Kool, the existing API worked as expected:

 Stream.finally go (Handle.toChunks fh)
    & Unicode.decodeUtf8Arrays'           -- Stream IO Char
    & Unicode.lines FL.toList                   -- Stream IO [Char]
    & Stream.map (\a -> (fp, a))              -- map with file path

    where

        go = do
            off <- liftIO $ hTell fh
            -- Stream finished persist handle offset
            liftIO $ putMVar mvar fh
            liftIO $ synchPersistentMap dbdir fp (show off)

**Comment by rnjtranjan** [comment]
Existing API does not solve the following use cases:
1. A file having data not ending with new line (means pending data to be written/saved). In this case incomplete line is fetched.

For example data at time : 

(initial)        t1-> 123456\n789
(next save) t2-> 123456\n789101112\n
						  
Ideally output should have two lines : 
L1 = 123456
L2 = 789101112

But current API  produces three lines:
L1 = 123456
L2 = 789
L3 = 101112

**Comment by rnjtranjan** [comment]
The use case mentioned is not likely to happen.

**Pull request closed without merging**
