### PR TITLE
Array bench cleanup

### PR DESCRIPTION
**Pull request by adithyaov**

### CODE REVIEW

**Comment by harendra-kumar** [comment]
I ran benchmarks against master:

```
Generating reports for Data.Array...
Removing benchmarks ["All.Data.Array/o-n-space.elimination.writeLastN.Max"] from column [default] run id [0]
Removing benchmarks ["All.Data.Array/o-n-heap.elimination.writeLastN.Max"] from column [default] run id [1]
Data.Array(cpuTime)
Benchmark                                                default(0)(μs) default(1) - default(0)(%)
-------------------------------------------------------- -------------- --------------------------
All.Data.Array/o-n-space.elimination.writeN                      106.53                   +2193.74
All.Data.Array/o-1-space.generation.writeN . fromList           5319.92                     +12.48
All.Data.Array/o-1-space.elimination.read                       2168.82                     +12.10
```

writeLastN.Max seems to be missing from both Data.Array and Data.Array.Foreign. And writeN seems to have a big regression. Can you take a look?

**Comment by adithyaov** [comment]
> writeLastN.Max seems to be missing from both Data.Array and Data.Array.Foreign. And writeN seems to have a big regression. Can you take a look?

1. `writeLastN.Max` Was reclassified as `o_n_heap` which it should have been earlier as well. But I've reverted this change, I'll make this later in another PR, or I can add a separate commit at the end.
2. `writeN` benchmark had a BUG earlier, as in, although `Data.Array` we were benchmarking `Data.Array.Foreign.writeN`.

```
import qualified Streamly.Data.Array.Foreign as A

...

o_n_heap_serial :: Int -> [Benchmark]
o_n_heap_serial value =
    [ bgroup "elimination"
        [ ...
            , benchFold "writeN" (S.fold (A.writeN value))
                (P.sourceUnfoldrM value)
         ]
    ]


```

**Comment by adithyaov** [comment]
I'm creating another PR to:
1. Track the bug fix
2. Store a proof of benchmark results

**Comment by adithyaov** [comment]
See https://github.com/composewell/streamly/pull/1409

**Review by harendra-kumar — APPROVED** [review]
I have not compared with the previous benchmarks for missing benchmarks. I assume you have done the due diligence on that.

**Comment by adithyaov** [comment]
> I have not compared with the previous benchmarks for missing benchmarks. I assume you have done the due diligence on that.

Here's the proof:

```
Generating reports for Data.Array...
Data.Array(cpuTime)
Benchmark                                                default(0)(ms) default(1) - default(0)(%)
-------------------------------------------------------- -------------- --------------------------
All.Data.Array/o-1-space.elimination.==                            3.15                     +18.49
All.Data.Array/o-1-space.elimination.<                             3.20                     +15.76
All.Data.Array/o-1-space.elimination.writeLastN.10                 1.67                     +14.91
All.Data.Array/o-1-space.elimination.min                           3.40                      +9.25
All.Data.Array/o-1-space.transformation.map                       15.97                      +7.42
All.Data.Array/o-1-space.elimination.foldl'                        3.27                      +6.36
All.Data.Array/o-1-space.transformationX4.scanl1'                 28.93                      +3.83
All.Data.Array/o-1-space.generation.writeN . intFromTo             3.35                      +1.88
All.Data.Array/o-1-space.generation.write . intFromTo              2.24                      +1.72
All.Data.Array/o-n-space.elimination.writeN                        2.03                      +1.53
All.Data.Array/o-1-space.generation.show                          36.04                      +0.80
All.Data.Array/o-1-space.elimination./=                            3.16                      +0.58
All.Data.Array/o-1-space.elimination.writeLastN.1                  1.54                      -1.67
All.Data.Array/o-1-space.transformation.scanl1'                    9.28                      -2.10
All.Data.Array/o-1-space.elimination.toStreamRev                   3.48                      -6.27
All.Data.Array/o-1-space.generation.read                         157.65                      -6.93
All.Data.Array/o-n-space.elimination.writeLastN.Max                4.99                      -7.16
All.Data.Array/o-1-space.elimination.read                          3.21                      -7.22
All.Data.Array/o-1-space.generation.writeN . unfoldr               3.45                      -7.35
All.Data.Array/o-1-space.generation.writeN . fromList              6.65                      -8.18
All.Data.Array/o-1-space.transformation.scanl'                    10.38                     -10.43
All.Data.Array/o-1-space.transformationX4.map                     49.81                     -10.79
All.Data.Array/o-1-space.transformationX4.scanl'                  28.46                     -22.85
All.Data.Array/o-1-space.elimination.id                            4.06                     -25.68
All.Data.Array/o-1-space.generation.fromList . intFromTo          10.61                     -47.92



Generating reports for Data.Array.Foreign...
Data.Array.Foreign(cpuTime)
Benchmark                                                                default(0)(Î¼s) default(1) - default(0)(%)
------------------------------------------------------------------------ -------------- --------------------------
All.Data.Array.Foreign/o-1-space.elimination.==                                   64.90                     +20.01
All.Data.Array.Foreign/o-1-space.elimination.read                                 73.89                     +16.56
All.Data.Array.Foreign/o-1-space.elimination.length . IsList.toList              124.72                     +10.13
All.Data.Array.Foreign/o-1-space.elimination.writeLastN.10                        79.24                      +9.73
All.Data.Array.Foreign/o-n-space.elimination.writeLastN.Max                      131.82                      +6.48
All.Data.Array.Foreign/o-1-space.generation.writeN . fromList                   1404.11                      +4.93
All.Data.Array.Foreign/o-1-space.elimination.min                                 130.34                      +4.02
All.Data.Array.Foreign/o-1-space.transformationX4.map                            312.79                      +1.52
All.Data.Array.Foreign/o-1-space.generation.write . intFromTo                    107.00                      +0.27
All.Data.Array.Foreign/o-1-space.transformation.scanl1'                          105.28                      +0.16
All.Data.Array.Foreign/o-1-space.transformation.map                              104.46                      -0.00
All.Data.Array.Foreign/o-1-space.generation.writeN . intFromTo                    58.13                      -0.01
All.Data.Array.Foreign/o-1-space.elimination.<                                   129.49                      -0.09
All.Data.Array.Foreign/o-1-space.generation.writeN . unfoldr                      58.04                      -0.14
All.Data.Array.Foreign/o-n-space.elimination.writeN                               57.84                      -0.23
All.Data.Array.Foreign/o-1-space.elimination.id                                   58.99                      -1.45
All.Data.Array.Foreign/o-1-space.generation.writeN . IsString.fromString        1496.30                      -2.93
All.Data.Array.Foreign/o-1-space.generation.read                              152732.00                      -5.31
All.Data.Array.Foreign/o-1-space.generation.show                               40122.40                      -5.55
All.Data.Array.Foreign/o-1-space.elimination./=                                   69.32                      -6.61
All.Data.Array.Foreign/o-1-space.transformationX4.scanl'                         335.92                      -8.58
All.Data.Array.Foreign/o-1-space.elimination.foldl'                              120.82                      -8.95
All.Data.Array.Foreign/o-1-space.transformationX4.scanl1'                        334.34                     -10.29
All.Data.Array.Foreign/o-1-space.generation.writeN . IsList.fromList            2456.03                     -10.61
All.Data.Array.Foreign/o-1-space.transformation.scanl'                           143.21                     -12.46
All.Data.Array.Foreign/o-1-space.elimination.writeLastN.1                        106.09                     -12.61
All.Data.Array.Foreign/o-1-space.elimination.toStreamRev                         105.04                     -22.00
All.Data.Array.Foreign/o-1-space.generation.fromList . intFromTo                2370.89                     -38.85


Generating reports for Data.Array.Prim...
Removing benchmarks ["All.Data.Array.Prim/o-1-space.elimination.writeLastN.1","All.Data.Array.Prim/o-1-space.elimination.writeLastN.10","All.Data.Array.Prim/o-n-space.elimination.writeLastN.Max"] from column [default] run id [0]
Data.Array.Prim(cpuTime)
Benchmark                                                     default(0)(Î¼s) default(1) - default(0)(%)
------------------------------------------------------------- -------------- --------------------------
All.Data.Array.Prim/o-1-space.elimination.==                           37.80                     +65.34
All.Data.Array.Prim/o-1-space.generation.writeN . intFromTo            38.39                     +62.96
All.Data.Array.Prim/o-1-space.elimination.<                            37.76                     +54.20
All.Data.Array.Prim/o-1-space.elimination.foldl'                       80.22                     +17.44
All.Data.Array.Prim/o-1-space.transformation.scanl'                   107.19                     +12.57
All.Data.Array.Prim/o-1-space.generation.writeN . unfoldr              52.07                     +11.66
All.Data.Array.Prim/o-1-space.elimination.id                           37.78                      +8.65
All.Data.Array.Prim/o-1-space.transformationX4.map                    278.27                      +0.22
All.Data.Array.Prim/o-1-space.transformationX4.scanl1'                293.59                      -0.25
All.Data.Array.Prim/o-1-space.generation.writeN . fromList           1048.35                      -1.80
All.Data.Array.Prim/o-1-space.transformation.map                       99.60                      -2.04
All.Data.Array.Prim/o-1-space.transformationX4.scanl'                 334.17                      -5.62
All.Data.Array.Prim/o-1-space.elimination.toStreamRev                  71.77                      -6.60
All.Data.Array.Prim/o-1-space.generation.show                       29232.00                      -9.21
All.Data.Array.Prim/o-n-space.elimination.writeN                       61.62                     -20.39
All.Data.Array.Prim/o-1-space.transformation.scanl1'                  126.33                     -29.62
All.Data.Array.Prim/o-1-space.generation.write . intFromTo            114.38                     -39.18
All.Data.Array.Prim/o-1-space.elimination./=                           57.46                     -51.63
All.Data.Array.Prim/o-1-space.elimination.min                          57.52                     -52.15
All.Data.Array.Prim/o-1-space.elimination.read                        115.53                     -60.16
All.Data.Array.Prim/o-1-space.generation.fromList . intFromTo        5619.05                    -488.75


Generating reports for Data.Array.Prim.Pinned...
Removing benchmarks ["All.Data.Array.Prim.Pinned/o-1-space.elimination.writeLastN.1","All.Data.Array.Prim.Pinned/o-1-space.elimination.writeLastN.10","All.Data.Array.Prim.Pinned/o-n-space.elimination.writeLastN.Max"] from column [default] run id [0]
Data.Array.Prim.Pinned(cpuTime)
Benchmark                                                            default(0)(Î¼s) default(1) - default(0)(%)
-------------------------------------------------------------------- -------------- --------------------------
All.Data.Array.Prim.Pinned/o-1-space.generation.writeN . intFromTo            41.01                     +43.97
All.Data.Array.Prim.Pinned/o-1-space.elimination.id                           40.95                     +43.04
All.Data.Array.Prim.Pinned/o-1-space.elimination.toStreamRev                  66.79                     +28.55
All.Data.Array.Prim.Pinned/o-1-space.transformation.scanl1'                   95.54                     +24.53
All.Data.Array.Prim.Pinned/o-n-space.elimination.writeN                       58.15                     +16.12
All.Data.Array.Prim.Pinned/o-1-space.generation.writeN . fromList            987.19                      +8.00
All.Data.Array.Prim.Pinned/o-1-space.elimination.read                         67.11                      +6.92
All.Data.Array.Prim.Pinned/o-1-space.elimination.foldl'                       92.71                      +6.62
All.Data.Array.Prim.Pinned/o-1-space.generation.show                       27513.50                      +2.30
All.Data.Array.Prim.Pinned/o-1-space.elimination./=                           37.79                      +1.30
All.Data.Array.Prim.Pinned/o-1-space.transformation.map                       98.15                      -0.47
All.Data.Array.Prim.Pinned/o-1-space.transformationX4.scanl1'                292.64                      -5.51
All.Data.Array.Prim.Pinned/o-1-space.transformationX4.map                    298.67                      -7.53
All.Data.Array.Prim.Pinned/o-1-space.transformationX4.scanl'                 317.00                      -9.68
All.Data.Array.Prim.Pinned/o-1-space.transformation.scanl'                   115.72                     -13.49
All.Data.Array.Prim.Pinned/o-1-space.generation.write . intFromTo             97.33                     -19.16
All.Data.Array.Prim.Pinned/o-1-space.elimination.<                            57.85                     -53.12
All.Data.Array.Prim.Pinned/o-1-space.elimination.min                          57.83                     -53.53
All.Data.Array.Prim.Pinned/o-1-space.generation.writeN . unfoldr              59.38                     -56.43
All.Data.Array.Prim.Pinned/o-1-space.elimination.==                           62.48                     -62.74
All.Data.Array.Prim.Pinned/o-1-space.generation.fromList . intFromTo        4374.52                    -332.10
```

**Pull request merged**
