### PR TITLE
Add a skip constructor to the stream type

### PR DESCRIPTION
**Pull request by Abhiroop**
This is a work in progress PR for fixing https://github.com/composewell/streamly/issues/90

The major operations in `vector` for which the Skip constructor exists like `filter`, `drop` etc they need to be modified still and the whole thing needs benchmarking. 

Also does the CPS encoding need to change as well to allow transformation between the two alternate representations?

### CODE REVIEW

**Comment by harendra-kumar** [comment]
I would suggest that you try it on just a couple of relevant operations and comment out the rest of the operations. That way you do not have to make all the changes before knowing whether it has the desired impact.

**Comment by Abhiroop** [comment]
These numbers are on an Intel Core i5 Processor. The comparisons are shown against `vector` which is able to leverage fusion and is the fastest among other streaming libraries.

## Benchmarks with Skip

```
Composed Operations x 4 (Lower is Better)(time)(Median)(Diff using min estimator)
Benchmark   vector(μs)(base) streamly(%)(-base)
----------- ---------------- ------------------
filter-scan        137522.15            +193.90
filter-drop          7027.87            +178.62
drop-scan          327172.69             +30.32
take-scan          374211.60             +11.06
filter-take          1367.04              +0.64
take-map             1383.34              +0.01
filter-map            819.87              -2.05
scan-map           478217.01              -5.32
drop-map             7124.62             -70.77
take-drop           32724.59             -89.48
```

```
Filtering  Operations x 4 (Lower is Better)(time)(Median)(Diff using min estimator)
Benchmark       vector(μs)(base) streamly(%)(-base)
--------------- ---------------- ------------------
dropWhile-true           1959.22              +4.10
takeWhile-true            656.18              +3.92
filter-even               651.32              +0.37
filter-all-in             685.80              +0.34
dropWhile-false         31877.75              +0.25
filter-all-out            660.73              -1.29
take-all                 1351.15              -1.45
drop-all                  981.48             -31.71
drop-one                 6897.82             -70.01
```
## Benchmarks without Skip (streamly-0.5.2)

```
Composed Operations x 4 (Lower is Better)(time)(Median)(Diff using min estimator)
Benchmark   vector(μs)(base) streamly(%)(-base)
----------- ---------------- ------------------
filter-take          1394.25            +995.77
filter-drop          6296.87            +113.55
drop-map             6978.72             +65.00
filter-map            663.91             +50.27
take-map             1346.74              +2.16
take-drop           30819.03              +1.24
filter-scan        139686.84             -48.89
drop-scan          391854.90             -65.63
take-scan          369179.51             -81.59
scan-map           466626.51             -85.28
```

```
Filtering  Operations x 4 (Lower is Better)(time)(Median)(Diff using min estimator)
Benchmark       vector(μs)(base) streamly(%)(-base)
--------------- ---------------- ------------------
filter-even               677.98            +202.54
drop-all                 1044.65            +129.21
dropWhile-true           2037.21             +69.83
drop-one                 6917.37             +48.94
filter-all-in             691.37             +44.53
filter-all-out            693.56              +0.95
take-all                 1347.89              -0.18
takeWhile-true            709.55              -2.77
dropWhile-false         33145.88             -66.36
```

**Comment by Abhiroop** [comment]
`filter-drop` with Skip was previously 178% slower than `vector`. A new implementation of `drop` as implemented in `vector` improves it considerably as observed by @pranaysashank .

It improves `drop-all` as well. Few functions like `take-drop` shows minor regressions(compared to `streamly-0.5.2`) but are still faster than `vector`

```
Composed Operations x 4 (Lower is Better)(time)(Median)(Diff using min estimator)
Benchmark   vector(μs)(base) streamly(%)(-base)
----------- ---------------- ------------------
filter-scan        160595.40            +143.09
drop-scan          364036.78             +26.61
take-scan          366582.61             +13.10
take-map             1379.57              +0.25
take-drop           30197.05              -0.02
drop-map             6728.82              -0.18
filter-map            698.35              -1.78
filter-drop          6335.64              -3.97
filter-take          1501.01              -5.21
scan-map           495187.06              -9.46
```

```
Filtering  Operations x 4 (Lower is Better)(time)(Median)(Diff using min estimator)
Benchmark       vector(μs)(base) streamly(%)(-base)
--------------- ---------------- ------------------
filter-all-out            713.36              +3.13
drop-all                 1002.23              +2.77
drop-one                 7014.66              +2.09
filter-even               685.09              +2.00
take-all                 1387.22              +0.75
dropWhile-true           2149.84              -0.55
filter-all-in             712.41              -2.05
dropWhile-false         37086.43              -4.63
takeWhile-true            709.23              -5.55
```

**Comment by harendra-kumar** [comment]
@Abhiroop can you please rebase on master and squash the commits?

**Comment by harendra-kumar** [comment]
This is cool! Good work @Abhiroop and @pranaysashank !

**Pull request merged**
