### PR TITLE
Only dispatch a new worker if we haven't reached the limit.

### LINKED ISSUE #181: `maxThreads` ignored unless `Rate` is also specified.
```
λ S.runStream . S.maxThreads 1 . S.asyncly $ S.replicateM 5 (threadDelay 1000000)
(1.01 secs, 722,616 bytes)
λ S.runStream . S.avgRate 10000 . S.maxThreads 1 . S.asyncly $ S.replicateM 5 (threadDelay 1000000)
(5.02 secs, 736,720 bytes)
```

I would expect both of these to take 5 seconds due to `maxThreads 1` in both of them.

### PR DESCRIPTION
**Pull request by luke-clifton**
Fixes #181

### CODE REVIEW

**Comment by harendra-kumar** [comment]
@luke-clifton thanks for the PR, I appreciate your time finding and fixing this. 

This fix breaks the previous fix targeted by commit cca869f7ed98fbe513cff1e67635917f9e16e113. You can see that by running these commands (please sync and rebase with master for the `no-charts` flag):

```
$ cabal new-build --flag dev --flag no-charts --disable-benchmarks maxrate
$ dist-newstyle/build/x86_64-osx/ghc-8.6.2/streamly-0.6.0/build/maxrate/maxrate
```

Compare the results of this test with and without the fix. You will notice that several tests now have the timings too far off the desired range. Note that if your machine is not powerful enough the very high rate tests might fail anyway in both cases.

So we can add something like the following, so that both with and without rate-control work well:

```
@@ -1426,10 +1426,13 @@ dispatchWorker yieldCount sv = do
                 Nothing -> return workerLimit
                 Just ref -> do
                     n <- liftIO $ readIORef ref
-                    return $
-                        case workerLimit of
-                            Unlimited -> Limited (fromIntegral n)
-                            Limited lim -> Limited $ min lim (fromIntegral n)
+                    case yieldRateInfo sv of
+                        Just _ -> return workerLimit
+                        Nothing ->
+                            return $
+                                case workerLimit of
+                                    Unlimited -> Limited (fromIntegral n)
+                                    Limited lim -> Limited $ min lim (fromIntegral n)
```

**Comment by harendra-kumar** [comment]
Note that the above mentioned problem is due to the `maxYields` mechanism which tries to restrict the number of yields. The `remainingWork` in the code above is related to `maxYields` internal combinator. We use `maxYields` to restrict the yields to, for example, the number of elements specified by a `take` on the stream. The fix above is just disabling that mechanism in case rate-control is enabled. 

The `maxYields` mechanism is hacky and has other problems too, see #160. We should perhaps consider removing it.

**Comment by luke-clifton** [comment]
That patch you posted doesn't work either. I don't currently have the time to dig into this much further unfortunately.

I guess I don't understand why limiting it they way I was breaks the tests you posted. I also don't see HOW that can be wrong. If `maxThreads` is set, I really don't want more than that being spawned ever. Thus imposing a hard limit seems like the right thing to do.

I'll see if I get some more time to take a look, but I'm pretty swamped at the moment.

**Comment by harendra-kumar** [comment]
@luke-clifton I may not have been clear enough. The patch that I posted is in addition to your previous change, it has to be applied on top of that. So the hard limit stays, I did not intend to remove it. What that patch does is fix the `maxYields` problem that I pointed out in previous update, this is applicable only when rate-control is used.

**Pull request closed without merging**
