### PR TITLE
Rename Unicode and Memory modules according the defined module structure

### LINKED ISSUE #652: Move Streamly.Data.Unicode to Streamly.Unicode
Like FileSystem/Network, `Unicode` can be a separate namespace directly under Streamly instead of under Data. This is also proposed in this: https://github.com/composewell/streamly/blob/module-org/design/module-organization.md .

We can deprecate the current Streamly.Data.Unicode and move it under streamly.

### PR DESCRIPTION
**Pull request by adithyaov**
CONTAINS BREAKING CHANGES

Closes #652 and #653

### CODE REVIEW

**Comment by adithyaov** [comment]
@harendra-kumar Please review & merge this once the CI passes.

**Comment by adithyaov** [comment]
We can remove `ArrayStream`.

**Review by harendra-kumar — COMMENTED** [review]
Looks good except that we may want to change the array module to `Data.Array.Foreign` instead.

**Review by harendra-kumar — APPROVED** [review]
For unicode arrays (or unicode strings) we perhaps do not care about Storable/Foreign in the name.  Chars are anyway Storable, and we do not care if the array is foreign or not.

**Pull request merged**
